name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: ksingh1505
          outputs: |
            dist/github-contribution-grid-snake.svg

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
